EXPERIMENT_PREFIX = 'EXPERIMENT_'
EXPERIMENT_STATUS = 'EXPERIMENT_STATUS'
TASK_QUEUE_PREFIX = 'TASK_QUEUE_'
EXPERIMENT_QUEUE_PREFIX = 'EXECUTION_QUEUE_'
DONE_QUEUE_PREFIX = 'DONE_QUEUE_'

EXPERIMENT_ID = 'EXPERIMENT_ID'
BLOCK_ID = 'BLOCK_ID'

WAITING = -1
EXECUTING = 1
DONE = 0

STARTED = 0
ENDED = 1

N_HIDDEN_LAYERS = 'n_hidden_layers'
N_NEURONS_HIDDEN_LAYERS = 'n_neurons_hidden_layers'
INIT_MODE = 'init_mode'
ACTIVATION = 'activation'

OPTIMIZER = 'optimizer'
LEARN_RATE = 'learn_rate'
MOMENTUM = 'momentum'

BATCH_SIZE = 'batch_size'
EPOCHS = 'epochs'
